RoomBooking/Controllers/RoomTypesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RoomBooking.Models;
using RoomBooking.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RoomBooking.Controllers
{
   // [Authorize]
    public class RoomTypesController : Controller
    {
        private readonly IGenericHotelService<RoomType> _hotelService;

        public RoomTypesController(IGenericHotelService<RoomType> genericHotelService)
        {
            _hotelService = genericHotelService;
        }

        // GET: RoomTypes
        public async Task<IActionResult> Index()
        {
            return View(await _hotelService.GetAllItemsAsync());
        }

        // GET: RoomTypes/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var roomType = await _hotelService.GetItemByIdAsync(id);


            if (roomType == null)
            {
                return NotFound();
            }

            var rooms = _hotelService.GetAllRooms().Where(x => x.RoomTypeID == id);
            ViewData["CategoryRooms"] = rooms;
            return View(roomType);
        }

        // GET: RoomTypes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: RoomTypes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,BasePrice,Description,ImageUrl")] RoomType roomType)
        {
            if (ModelState.IsValid)
            {
                roomType.ID = Guid.NewGuid().ToString();
                await _hotelService.CreateItemAsync(roomType);
                return RedirectToAction(nameof(Index));
            }
            return View(roomType);
        }

        // GET: RoomTypes/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var roomType = await _hotelService.GetItemByIdAsync(id);
            if (roomType == null)
            {
                return NotFound();
            }
            return View(roomType);
        }

        // POST: RoomTypes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("ID,Name,BasePrice,Description,ImageUrl")] RoomType roomType)
        {
            if (id != roomType.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _hotelService.EditItemAsync(roomType);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (_hotelService.GetItemByIdAsync(id) == null)
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(roomType);
        }

        // GET: RoomTypes/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var roomType = await _hotelService.GetItemByIdAsync(id);
            if (roomType == null)
            {
                return NotFound();
            }

            return View(roomType);
        }

        // POST: RoomTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var roomType = await _hotelService.GetItemByIdAsync(id);
            await _hotelService.DeleteItemAsync(roomType);
            return RedirectToAction(nameof(Index));
        }
    }
}

RoomBooking/Controllers/RoomsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RoomBooking.Models;
using RoomBooking.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RoomBooking.Controllers
{
    //[Authorize]
    public class RoomsController : Controller
    {
        private readonly IGenericHotelService<Room> _hotelService;

        public RoomsController(IGenericHotelService<Room> genericHotelService)
        {
            _hotelService = genericHotelService;
        }

        // GET: Rooms
        public IActionResult Index()
        {
            return View(_hotelService.GetAllRoomsAndRoomTypes());
        }

        // GET: Rooms/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = _hotelService.GetAllRooms().SingleOrDefault(x => x.ID == id);


            if (room == null)
            {
                return NotFound();
            }

            var ImagesAndFeatures = await _hotelService.GetRoomFeaturesAndImagesAsync(room);
            ViewData["Features"] = ImagesAndFeatures.Features;
            ViewData["Images"] = ImagesAndFeatures.Images;
            return View(room);
        }

        // GET: Rooms/Create
        public IActionResult Create()
        {
            var RoomTypes = _hotelService.GetAllRoomTypesAsync().Result;
            ViewData["RoomTypeID"] = new SelectList(RoomTypes, "ID", "Name");

            var room = new Room();
            ViewData["Features"] = _hotelService.PopulateSelectedFeaturesForRoom(room);


            return View();
        }

        // POST: Rooms/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Number,RoomTypeID,Price,Available,Description,MaximumGuests")] Room room, string[] SelectedFeatureIDs, string[] imageIDs)
        {
            if (ModelState.IsValid)
            {
                room.ID = Guid.NewGuid().ToString();
                await _hotelService.CreateItemAsync(room);
                _hotelService.UpdateRoomFeaturesList(room, SelectedFeatureIDs);
                _hotelService.UpdateRoomImagesList(room, imageIDs);
                return RedirectToAction(nameof(Index));
            }
            ViewData["Features"] = _hotelService.PopulateSelectedFeaturesForRoom(room);
            var ImagesAndFeatures = await _hotelService.GetRoomFeaturesAndImagesAsync(room);
            ViewData["Images"] = ImagesAndFeatures.Images;
            return View(room);
        }


        // GET: Rooms/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = await _hotelService.GetItemByIdAsync(id);
            if (room == null)
            {
                return NotFound();
            }
            var RoomTypes = _hotelService.GetAllRoomTypesAsync().Result;
            ViewData["RoomTypeID"] = new SelectList(RoomTypes, "ID", "Name", room.RoomType.ID);

            ViewData["Features"] = _hotelService.PopulateSelectedFeaturesForRoom(room);
            var ImagesAndFeatures = await _hotelService.GetRoomFeaturesAndImagesAsync(room);
            ViewData["Images"] = ImagesAndFeatures.Images;
            return View(room);
        }

        // POST: Rooms/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("ID,Number,RoomTypeID,Price,Available,Description,MaximumGuests")] Room room, string[] SelectedFeatureIDs, string[] imageIDs)
        {
            if (id != room.ID)
            {
                return NotFound();
            }


            if (ModelState.IsValid)
            {
                try
                {
                    await _hotelService.EditItemAsync(room);
                    _hotelService.UpdateRoomFeaturesList(room, SelectedFeatureIDs);
                    _hotelService.UpdateRoomImagesList(room, imageIDs);

                }
                catch (DbUpdateConcurrencyException)
                {
                    if (_hotelService.GetItemByIdAsync(id) == null)
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            var RoomTypes = _hotelService.GetAllRoomTypesAsync().Result;
            ViewData["RoomTypeID"] = new SelectList(RoomTypes, "ID", "ID", room.RoomTypeID);
            ViewData["Features"] = _hotelService.PopulateSelectedFeaturesForRoom(room);
            var ImagesAndFeatures = await _hotelService.GetRoomFeaturesAndImagesAsync(room);
            ViewData["Images"] = ImagesAndFeatures.Images;
            return View(room);
        }




        // GET: Rooms/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = await _hotelService.GetItemByIdAsync(id);
            if (room == null)
            {
                return NotFound();
            }

            return View(room);
        }

        // POST: Rooms/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {

            var roomType = await _hotelService.GetItemByIdAsync(id);
            await _hotelService.DeleteItemAsync(roomType);
            return RedirectToAction(nameof(Index));
        }


        //This method simply populates a ViewBag with selected features pertaining to the room in question
        //using the SelectedRoomFeatureViewModel which contains a feature and a boolean indicating if the checkbox should be selected or not.



    }
}

RoomBooking/Views/Shared/_Layout.cshtml
@*<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - RoomBooking</title>
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </head>
    <body>
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RoomBooking</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <partial name="_LoginPartial" />
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2021 - RoomBooking - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @RenderSection("Scripts", required: false)
    </body>
    </html>*@

@using Microsoft.AspNetCore.Identity
@using RoomBooking.Models

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Hotel Management System is a software system designed to manage your Hotel.">
    <title>Le Meridien Ibom Hotel</title>
    <!-- ========== Css Files ========== -->
    <link href="~/css/root.css" rel="stylesheet">
</head>
<body>
    <!-- Start Page Loading -->
    <div class="loading"><img src="~/img/loading.gif" alt="loading-img"></div>
    <!-- End Page Loading -->
    <!-- //////////////////////////////////////////////////////////////////////////// -->
    <!-- START TOP -->
    <div id="top" class="clearfix">
        <!-- Start App Logo -->
        <div class="applogo">
            <a href="index.html" class="logo">Meridian</a>
        </div>
        <!-- End App Logo -->
        <!-- Start Sidebar Show Hide Button -->
        <a href="#" class="sidebar-open-button"><i class="fa fa-bars"></i></a>
        <a href="#" class="sidebar-open-button-mobile"><i class="fa fa-bars"></i></a>
        <!-- End Sidebar Show Hide Button -->
        <!-- Start Searchbox -->
        <form class="searchform">
            <input type="text" class="searchbox" id="searchbox" placeholder="Search">
            <span class="searchbutton"><i class="fa fa-search"></i></span>
        </form>
        <!-- End Searchbox -->
        <!-- Start Sidepanel Show-Hide Button -->
        <a href="#sidepanel" class="sidepanel-open-button"><i class="fa fa-outdent"></i></a>
        <!-- End Sidepanel Show-Hide Button -->
        <!-- Start Top Right -->
        <ul class="top-right">
            <li class="dropdown link">
                <a href="#" data-toggle="dropdown" class="dropdown-toggle hdbutton">Create New <span class="caret"></span></a>
                <ul class="dropdown-menu dropdown-menu-list">
                    <li><a asp-action="Create" asp-controller="Rooms"><i class="fa falist fa-bed"></i>Room</a></li>
                    <li><a asp-action="Create" asp-controller="RoomTypes"><i class="fa falist fa-folder-open"></i>Room Category</a></li>
                    <li><a asp-action="Create" asp-controller="Features"><i class="fa falist fa-check-square-o"></i>Feature</a></li>
                    <li><a asp-action="Create" asp-controller="Bookings"><i class="fa falist fa-calendar"></i>Booking</a></li>
                </ul>
            </li>

            <li class="dropdown link">
                <a href="#" data-toggle="dropdown" class="dropdown-toggle profilebox"><img src="~/img/profileimg.png" alt="img"><b>@UserManager.GetUserName(User)</b><span class="caret"></span></a>
                <form asp-area="" asp-controller="Account" asp-action="Logout" method="post" id="logoutForm" class="navbar-right">
                    <ul class="dropdown-menu dropdown-menu-list dropdown-menu-right">
                        <li role="presentation" class="dropdown-header">Profile</li>
                        <li><a href="#"><i class="fa falist fa-inbox"></i>Inbox<span class="badge label-danger">4</span></a></li>
                        <li><a href="#"><i class="fa falist fa-file-o"></i>Files</a></li>
                        <li><a href="#"><i class="fa falist fa-wrench"></i>Settings</a></li>
                        <li class="divider"></li>
                        <li><a href="#"><i class="fa falist fa-lock"></i> Lockscreen</a></li>
                        <li><button type="submit"><i class="fa falist fa-power-off"></i> Logout</button></li>
                    </ul>
                </form>
            </li>
        </ul>
        <!-- End Top Right -->
    </div>
    <!-- END TOP -->
    <!-- //////////////////////////////////////////////////////////////////////////// -->
    <!-- //////////////////////////////////////////////////////////////////////////// -->
    <!-- START SIDEBAR -->
    <div class="sidebar clearfix sidebar-colorful">
        <ul class="sidebar-panel nav">
            <li>
                <a asp-action="index" asp-controller="rooms"><span class="icon color7"><i class="fa fa-bed"></i></span>Rooms</a>
            </li>
            <li>
                <a asp-action="index" asp-controller="roomtypes"><span class="icon color2"><i class="fa fa-folder-open"></i></span>Room Categories</a>
            </li>
            <li>
                <a asp-action="index" asp-controller="bookings"><span class="icon color3"><i class="fa fa-calendar"></i></span>Bookings</a>

            </li>
            <li>
                <a asp-action="index" asp-controller="features"><span class="icon color7"><i class="fa fa-check-square-o"></i></span>Features</a>
            </li>
            <li><a href="#"><span class="icon color11"><i class="fa fa-diamond"></i></span>Reviews</a></li>
            <li><a asp-action="index" asp-controller="images"><span class="icon color1"><i class="fa fa-image"></i></span>Media</a></li>
            <li>
                <a asp-action="index" asp-controller="manage"><span class="icon color10"><i class="fa fa-user"></i></span>Account</a>

            </li>
        </ul>
    </div>
    <!-- END SIDEBAR -->
    <!-- //////////////////////////////////////////////////////////////////////////// -->
    <!-- //////////////////////////////////////////////////////////////////////////// -->
    <!-- START CONTENT -->
    <div class="content">
        @RenderBody()
        <!-- END CONTAINER -->
        <!-- //////////////////////////////////////////////////////////////////////////// -->
        <!-- Start Footer -->
        <div class="row footer">
            <div class="col-md-6 text-left">
                Copyright © 2018 <a href="https://github.com/Johnesan/TheHotelApplication" target="_blank">The Hotel Application.</a> All rights reserved.
            </div>
            <div class="col-md-6 text-right">
                Design and Developed by <a href="https://github.com/Johnesan" target="_blank">John Esan</a>
            </div>
        </div>
        <!-- End Footer -->

    </div>
    <!-- End Content -->
    <!-- //////////////////////////////////////////////////////////////////////////// -->
    <!-- //////////////////////////////////////////////////////////////////////////// -->
    <!-- START SIDEPANEL -->
    <!-- END SIDEPANEL -->
    <!-- //////////////////////////////////////////////////////////////////////////// -->
    <!-- ================================================
    jQuery Library
    ================================================ -->
    <script type="text/javascript" src="~/js/jquery.min.js"></script>
    <!-- ================================================
    Bootstrap Core JavaScript File
    ================================================ -->
    <script src="~/js/bootstrap/bootstrap.min.js"></script>
    <!-- ================================================
    Plugin.js - Some Specific JS codes for Plugin Settings
    ================================================ -->
    <script type="text/javascript" src="~/js/plugins.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>